version: '3.8'
services:
  postgres-validation:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      platforms:
        - linux/arm64
    container_name: walg-postgres-validation
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: testdb
    volumes:
      - ./backups/validation_restore:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - "5433:5432"
    command: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
